USE LounesAdjou_StreamingPlatform;

-- Disable foreign key checks to avoid constraint issues
SET FOREIGN_KEY_CHECKS = 0;

-- Truncate all tables
TRUNCATE TABLE NOTE;
TRUNCATE TABLE COMMANDE;
TRUNCATE TABLE ACTEUR_FILM;
TRUNCATE TABLE EQUIPE_FILM;
TRUNCATE TABLE FILM_CATEGORIE;
TRUNCATE TABLE FILM_LANGUE;
TRUNCATE TABLE ABONNEMENT;
TRUNCATE TABLE CARTE_CREDIT;
TRUNCATE TABLE FILM;
TRUNCATE TABLE PERSONNE;
TRUNCATE TABLE CATEGORIE;
TRUNCATE TABLE LANGUE;
TRUNCATE TABLE COMPAGNIE;
TRUNCATE TABLE CLIENT;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;